import assert from 'node:assert/strict';
import worker from '../workers/gistda-flood.mjs';
const store = new Map();
globalThis.caches = {default: {match: async k => store.get(k.url)?.clone(), put: async(k, r) => store.set(k.url, r)}};
const origin = 'https://occhrh-dev.github.io';
const env = {GISTDA_API_KEY:'TEST_SECRET_DO_NOT_EXPOSE'};
const req = (days = '1', method = 'GET', allowed = true) => new Request('https://test.example/flood?days='+days,
  {method, headers: allowed ? {Origin: origin} : {}});
const shape = {type:'Polygon',coordinates:[[[101,12],[102,12],[102,13],[101,12]]]};
const feature = {type:'Feature', geometry: shape, properties:{pv_idn:'21',pv_tn:'ระยอง',ap_tn:'แกลง',tb_tn:'ชากพง',
  file_name:'S1D_20260910_0551, rd2_20260926_0613',_createdBy:'PRIVATE', links:'TEST_SECRET_DO_NOT_EXPOSE'}};
let calls = 0;
globalThis.fetch = async(url, options) => {
  url = new URL(url);
  calls++;
  assert.equal(url.hostname, 'api-gateway.gistda.or.th');
  assert.equal(url.searchParams.get('pv_idn'),'21');
  assert.equal(options.headers['API-Key'],env.GISTDA_API_KEY);
  assert.equal(options.redirect,'manual');
  assert.ok(!url.toString().includes(env.GISTDA_API_KEY));
  const offset = Number(url.searchParams.get('offset'));
  const features = Array.from({length:offset ? 1 : 100},()=>feature);
  return new Response(JSON.stringify({type:'FeatureCollection', features, numberReturned:features.length,
    numberMatched:101, timeStamp:'2026-10-05T00:00:00Z',links:[{href:env.GISTDA_API_KEY}]}));
};
assert.equal((await worker.fetch(req('3'),env)).status,400);
assert.equal((await worker.fetch(req('1','POST'),env)).status,405);
assert.equal((await worker.fetch(req('1','GET',false),env)).status,403);
assert.equal((await worker.fetch(req(),{})).status,503);
assert.equal(calls,0);
const response = await worker.fetch(req('30'),env);
assert.equal(response.status,200);
assert.equal(calls,2,'Pagination fetches all records');
const text = await response.text();
assert.ok(!text.includes(env.GISTDA_API_KEY));
assert.ok(!text.includes('PRIVATE'));
const data=JSON.parse(text);
assert.equal(data.features.length,101);
assert.equal(data.meta.complete,true);
assert.equal(data.meta.days,30);
assert.equal(data.features[0].properties.imageDates,'2026-09-10, 2026-09-26');
assert.deepEqual(data.features[0].geometry,shape);
await worker.fetch(req('30'),env);
assert.equal(calls,2,'Cached data avoids upstream calls');
store.clear();
globalThis.fetch = async()=>new Response(JSON.stringify({type:'FeatureCollection',features:[],numberMatched:0,numberReturned:0}));
assert.equal((await (await worker.fetch(req('1'),env)).json()).meta.numberMatched,0);
store.clear();
globalThis.fetch = async()=>new Response('Secret upstream URL '+env.GISTDA_API_KEY,{status:401});
assert.deepEqual(await (await worker.fetch(req('7'),env)).json(),{error:'KEY_REJECTED',upstreamStatus:401});
store.clear();
globalThis.fetch = async()=>new Response(JSON.stringify({type:'FeatureCollection',features:[feature],numberMatched:101,numberReturned:1}));
assert.equal((await worker.fetch(req(),env)).status,503,'Never display incomplete pages as a complete dataset');
store.clear();
globalThis.fetch = async()=>new Response(JSON.stringify({type:'FeatureCollection',features:[],numberMatched:2001,numberReturned:0}));
assert.deepEqual(await (await worker.fetch(req(),env)).json(),{error:'DATA_TOO_LARGE'});
store.clear();
globalThis.fetch = async()=>new Response(JSON.stringify({type:'FeatureCollection',features:[{...feature,properties:{pv_idn:'10'}}],numberMatched:1,numberReturned:1}));
assert.deepEqual(await (await worker.fetch(req(),env)).json(),{error:'INVALID_DATA'});
console.log('PASS: fixed origin/province/periods, secret stripping, geometry, dates, complete pagination, cache, empty data and safe failures');
